spring:
  profiles:
    default: dev
    active: dev
  security:
    user:
      name: admin
      password: admin
  jpa:
    hibernate:
      ddl-auto: none
server:
  error:
    path: /error

logging:
  level:
    org.springframework.web: "info"


---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/radshare
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER_3306}
    password: ${DB_PASS_3306}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

