spring:
  profiles:
    default: dev
    active: dev
  security:
    user:
      name: admin
      password: admin
  jpa:
    hibernate:
      ddl-auto: none
server:
  error:
    path: /error

logging:
  level:
    org.springframework.web: "info"


---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/voidrelics
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${DB_PASS_3306}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

