spring:
  profiles:
    default: dev
    active: dev
  jpa:
    hibernate:
      ddl-auto: none

  devtools.restart.enabled: false

server:
  error:
    path: /error
    include-stacktrace: never

logging:
  level:
    org.springframework.web: "info"

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/voidrelics
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${DB_PASS_3306}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

